name: Environment windows

runs:
  using: "composite"

  steps:
    - name: Set environment variable for work package url (pull request) windows.
      if: github.event_name == 'pull_request'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_OWNER_LOGIN: ${{ github.event.pull_request.head.repo.owner.login }}
      with:
        script: |
          core.exportVariable('WORK_PACKAGE_URL', `https://github.com/${process.env.GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_OWNER_LOGIN}/`);
          core.exportVariable('BRANCH_NAME', process.env.GITHUB_HEAD_REF);
          core.exportVariable('FULL_BRANCH_NAME', `dev-${process.env.GITHUB_HEAD_REF}`);

    - name: Set environment variable for work package url (push) windows.
      if: github.event_name == 'push'
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      env:
        GITHUB_EVENT_REPOSITORY_OWNER_LOGIN: ${{ github.event.repository.owner.login }}
      with:
        script: |
          core.exportVariable('WORK_PACKAGE_URL', `https://github.com/${process.env.GITHUB_EVENT_REPOSITORY_OWNER_LOGIN}/`);
          core.exportVariable('BRANCH_NAME', process.env.GITHUB_REF_NAME);
          core.exportVariable('FULL_BRANCH_NAME', `dev-${process.env.GITHUB_REF_NAME}`);
