name: Install packages

inputs:
  packages:
    description: List of packages to install, for example '["db", "db-sqlite"]'
    required: true
    type: string
  composer-root-version:
    description: Composer root version.
    default: dev-master
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - if: ${{ fromJSON(inputs.packages)[0] != '' }}
      name: Install ${{ fromJSON(inputs.packages)[0] }}.
      uses: yiisoft/actions/install-packages/install-package@install-subpackage
      with:
        package: ${{ fromJSON(inputs.packages)[0] }}
        composer-root-version: ${{ inputs.composer-root-version }}

    - if: ${{ fromJSON(inputs.packages)[1] != '' }}
      name: Install ${{ fromJSON(inputs.packages)[1] }}.
      uses: yiisoft/actions/install-packages/install-package@install-subpackage
      with:
        package: ${{ fromJSON(inputs.packages)[1] }}
        composer-root-version: ${{ inputs.composer-root-version }}

    - if: ${{ fromJSON(inputs.packages)[2] != '' }}
      name: Install ${{ fromJSON(inputs.packages)[2] }}.
      uses: yiisoft/actions/install-packages/install-package@install-subpackage
      with:
        package: ${{ fromJSON(inputs.packages)[2] }}
        composer-root-version: ${{ inputs.composer-root-version }}

    - if: ${{ fromJSON(inputs.packages)[3] != '' }}
      name: Install ${{ fromJSON(inputs.packages)[3] }}.
      uses: yiisoft/actions/install-packages/install-package@install-subpackage
      with:
        package: ${{ fromJSON(inputs.packages)[3] }}
        composer-root-version: ${{ inputs.composer-root-version }}

    - if: ${{ fromJSON(inputs.packages)[4] != '' }}
      name: Install ${{ fromJSON(inputs.packages)[4] }}.
      uses: yiisoft/actions/install-packages/install-package@install-subpackage
      with:
        package: ${{ fromJSON(inputs.packages)[4] }}
        composer-root-version: ${{ inputs.composer-root-version }}
