name: changelog

on:
  workflow_call:

permissions:
  contents: read

jobs:
  changelog:
    name: Check CHANGELOG.md
    if: github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check CHANGELOG.md updated
        run: |
          if ! git diff --name-only origin/master...HEAD | grep -qx 'CHANGELOG.md'; then
            message="%0A"
            message+="::error::%0AThis pull request changes primary files but does not update CHANGELOG.md.%0A"
            message+="%0A"
            message+="See the changelog documentation here:%0A"
            message+="https://yiisoft.github.io/docs/internals/021-changelog-upgrade.html#changelog"
            message+="%0A"
            echo "${message}"
            exit 1
          fi
