name: codeception

on:
  workflow_call:
    inputs:
      codeception-command:
        description: Codeception command to run.
        default: vendor/bin/codecept run --coverage-xml
        required: false
        type: string
      coverage:
        description: Generate code coverage report.
        default: pcov
        required: false
        type: string
      composer-command:
        description: Composer command to run.
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      debug:
        description: Debug mode.
        default: false
        required: false
        type: boolean
      extensions:
        description: List of PHP extensions to install.
        default:
        required: false
        type: string
      ini-values:
        description: Initial values for PHP configuration.
        default: date.timezone='UTC'
        required: false
        type: string
      os:
        description: OS to test, separated by comma.
        required: true
        type: string
      php:
        description: PHP versions to test, separated by comma.
        required: true
        type: string
      tools:
        description: Tools to install, separated by comma.
        default:
        required: false
        type: string
      codecovVerbose:
        description: Specify whether the Codecov output should be verbose.
        default: false
        required: false
        type: boolean
    secrets:
      CODECOV_TOKEN:
        description: Codecov upload token
        required: false
      codecovToken:
        description: Deprecated, use CODECOV_TOKEN
        required: false

permissions:
  contents: read

jobs:
  codeception:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      key: cache-v1
      YII_C3: true

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45
        with:
          coverage: ${{ inputs.coverage }}
          extensions: ${{ inputs.extensions }}
          ini-values: ${{ inputs.ini-values }}
          php-version: ${{ matrix.php }}
          tools: ${{ inputs.tools }}

      - name: Determine composer cache directory on Linux.
        if: matrix.os == 'ubuntu-latest'
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Determine composer cache directory on Windows.
        if: matrix.os == 'windows-latest'
        run: echo "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache dependencies installed with composer.
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Update composer.
        run: composer self-update

      - name: Install dependencies with composer.
        if: runner.os != 'Windows'
        run: |
          printf '%s\n' "$INPUTS_COMPOSER_COMMAND" > "$RUNNER_TEMP/composer-command.sh"
          bash -e "$RUNNER_TEMP/composer-command.sh"
        env:
          INPUTS_COMPOSER_COMMAND: ${{ inputs.composer-command }}

      - name: Install dependencies with composer.
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Set-Content -Path "$env:RUNNER_TEMP\composer-command.ps1" -Value $env:INPUTS_COMPOSER_COMMAND
          & "$env:RUNNER_TEMP\composer-command.ps1"
        env:
          INPUTS_COMPOSER_COMMAND: ${{ inputs.composer-command }}

      - name: Run tests with codeception with code coverage with shell bash.
        if: matrix.os == 'ubuntu-latest'
        continue-on-error:  ${{ inputs.debug }}
        run: |
          printf '%s\n' "$INPUTS_CODECEPTION_COMMAND" > "$RUNNER_TEMP/codeception-command.sh"
          bash -e "$RUNNER_TEMP/codeception-command.sh"
        env:
          INPUTS_CODECEPTION_COMMAND: ${{ inputs.codeception-command }}

      - name: Run tests with codeception with code coverage with shell powershell.
        if: matrix.os == 'windows-latest'
        continue-on-error:  ${{ inputs.debug }}
        run: |
          Set-Content -Path "$env:RUNNER_TEMP\codeception-command.ps1" -Value $env:INPUTS_CODECEPTION_COMMAND
          & "$env:RUNNER_TEMP\codeception-command.ps1"
        shell: powershell
        env:
          INPUTS_CODECEPTION_COMMAND: ${{ inputs.codeception-command }}

      - name: Upload coverage to Codecov.
        if: matrix.os == 'ubuntu-latest' && matrix.php == '8.1' && inputs.debug == false
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN || secrets.codecovToken }}
          files: tests/_output/coverage.xml
          verbose: ${{ inputs.codecovVerbose }}

      - name: Archive codeception results.
        if: ${{ inputs.debug }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: output
          path: ./runtime/tests/_output

      - name: Download all workflow run artifacts.
        if: ${{ inputs.debug }}
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
