name: db-mysql

on:
  workflow_call:
    inputs:
      install-db:
        description: Specifies whether to install `yiisoft/db`.
        default: true
        required: false
        type: boolean
      install-mysql:
        description: Specifies whether to install `yiisoft/mysql`.
        default: true
        required: false
        type: boolean
      mysql:
        description: MySQL version to test.
        default: latest
        required: false
        type: string
      php:
        description: PHP versions to test in JSON format.
        default: '["8.1","8.2","8.3","8.4","8.5"]'
        required: false
        type: string
      codecov-php:
        description: PHP version to upload coverage to Codecov.
        default: 8.5
        required: false
        type: string

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    env:
      composer-root-version: 2.0.0
      db-composer-root-version: 2.0.1
      extensions: pdo_mysql

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    services:
      mysql:
        image: mysql:${{ inputs.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-mysql
        if: ${{ inputs.install-mysql }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          composer-root-version: ${{ env.composer-root-version }}
          package: db-mysql

      - name: Install yiisoft/db package.
        if: ${{ inputs.install-db }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          composer-root-version: ${{ env.db-composer-root-version }}
          package: db

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Mysql --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: ${{ matrix.php == inputs.codecov-php }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
