name: db-mssql

on:
  workflow_call:
    inputs:
      php:
        description: PHP version to test.
        default: 8.5
        required: false
        type: string

jobs:
  tests:
    name: PHP ${{ inputs.php }}

    env:
      extensions: pdo_sqlsrv

    runs-on: windows-latest

    steps:
      - name: Install SQL Server on Windows.
        run: choco install sql-server-express --version=2017.20190916 -y --no-progress --ia="'/Q /SUPPRESSPRIVACYSTATEMENTNOTICE /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /INSTANCEID=MSSQLSERVER /INSTANCENAME=MSSQLSERVER /UPDATEENABLED=FALSE /SECURITYMODE=SQL /TCPENABLED=1 /SAPWD=YourStrong!Passw0rd'"

      - name: Create database.
        run: sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'

      - name: Checkout.
        uses: actions/checkout@v6

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-mssql
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db-mssql' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db-mssql

      - name: Install yiisoft/db package.
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db

      - name: Run mssql tests with phpunit and code coverage.
        run: vendor/bin/phpunit --testsuite Mssql --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations
