name: db-mssql

on:
  workflow_call:
    inputs:
      install-db:
        description: Specifies whether to install `yiisoft/db`. It is false only when running from `yiisoft/db`.
        default: true
        required: false
        type: boolean
      install-mssql:
        description: Specifies whether to install `yiisoft/mssql`. It is false only when running from `yiisoft/mssql`.
        default: true
        required: false
        type: boolean
      mssql:
        description: MSSQL version to test.
        default: 2022-latest
        required: false
        type: string
      php:
        description: PHP versions to test in JSON format.
        default: '["8.1","8.2","8.3","8.4","8.5"]'
        required: false
        type: string
      codecov-php:
        description: PHP version to upload coverage to Codecov.
        default: 8.5
        required: false
        type: string

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    env:
      # Sets composer root version for dependency compatibility. Required when running from `yiisoft/db` package.
      COMPOSER_ROOT_VERSION: ${{ inputs.install-db && 'dev-master' || '2.0.1' }}
      db-composer-root-version: 2.0.1
      mssql-composer-root-version: 2.0.0
      extensions: pdo_sqlsrv

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:${{ inputs.mssql }}
        env:
          SA_PASSWORD: YourStrong!Passw0rd
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        options: --name=mssql --health-cmd="/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install ODBC driver.
        run: |
          sudo curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get clean
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Create MS SQL Database.
        run: docker exec -i mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'

      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-mssql
        if: ${{ inputs.install-mssql }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          composer-root-version: ${{ env.mssql-composer-root-version }}
          package: db-mssql

      - name: Install yiisoft/db package.
        if: ${{ inputs.install-db }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          composer-root-version: ${{ env.db-composer-root-version }}
          package: db

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Mssql --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: ${{ matrix.php == inputs.codecov-php }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
