name: db-oracle

on:
  workflow_call:
    inputs:
      oracle:
        description: Oracle version to test.
        default: latest
        required: false
        type: string
      php:
        description: PHP versions to test, in JSON format.
        default: '["8.1","8.2","8.3","8.4","8.5"]'
        required: false
        type: string
      codecov-php:
        description: PHP version to upload coverage to Codecov.
        default: 8.5
        required: false
        type: string
    secrets:
      CODECOV_TOKEN:
        description: Codecov upload token
        required: false

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    env:
      extensions: pdo_oci

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    services:
      oci:
        image: gvenzl/oracle-xe:${{ inputs.oracle }}
        ports:
          - 1521:1521
        env:
          ORACLE_DATABASE: yiitest
          ORACLE_PASSWORD: root
        options: >-
          --name=oci
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Configure Database.
        run: docker exec -i oci bash -c "sqlplus -s system/root@XE <<< 'ALTER USER system DEFAULT TABLESPACE USERS;'"

      - name: Checkout.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-oracle
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db-oracle' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db-oracle

      - name: Install yiisoft/db package.
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Oracle --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: ${{ matrix.php == inputs.codecov-php }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
