name: db-pgsql

on:
  workflow_call:
    inputs:
      pgsql:
        description: Postgres version to test.
        default: 18
        required: false
        type: string
      php:
        description: PHP versions to test, in JSON format.
        default: '["8.1","8.2","8.3","8.4","8.5"]'
        required: false
        type: string
      codecov-php:
        description: PHP version to upload coverage to Codecov.
        default: 8.5
        required: false
        type: string
    secrets:
      CODECOV_TOKEN:
        description: Codecov upload token
        required: false

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    env:
      extensions: pdo_pgsql

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    services:
      postgres:
        image: postgres:${{ inputs.pgsql }}
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-pgsql
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db-pgsql' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db-pgsql

      - name: Install yiisoft/db package.
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Pgsql --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: ${{ matrix.php == inputs.codecov-php }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
