name: db-pgsql

on:
  workflow_call:
    inputs:
      install-db:
        description: Specifies whether to install `yiisoft/db`. It is false only when running from `yiisoft/db`.
        default: true
        required: false
        type: boolean
      install-pgsql:
        description: Specifies whether to install `yiisoft/pgsql`. It is false only when running from `yiisoft/pgsql`.
        default: true
        required: false
        type: boolean
      pgsql:
        description: Postgres version to test.
        default: 18
        required: false
        type: string
      php:
        description: PHP versions to test in JSON format.
        default: '["8.1","8.2","8.3","8.4","8.5"]'
        required: false
        type: string
      codecov-php:
        description: PHP version to upload coverage to Codecov.
        default: 8.5
        required: false
        type: string

jobs:
  tests:
    name: PHP ${{ matrix.php }}

    env:
      # Sets composer root version for dependency compatibility. Required when running from `yiisoft/db` package.
      COMPOSER_ROOT_VERSION: ${{ inputs.install-db && 'dev-master' || '2.0.1' }}
      db-composer-root-version: 2.0.1
      pgsql-composer-root-version: 2.0.1
      extensions: pdo_pgsql

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ${{ fromJson(inputs.php) }}

    services:
      postgres:
        image: postgres:${{ inputs.pgsql }}
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-pgsql
        if: ${{ inputs.install-pgsql }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          composer-root-version: ${{ env.pgsql-composer-root-version }}
          package: db-pgsql

      - name: Install yiisoft/db package.
        if: ${{ inputs.install-db }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          composer-root-version: ${{ env.db-composer-root-version }}
          package: db

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Pgsql --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: ${{ matrix.php == inputs.codecov-php }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
