name: db-sqlite

on:
  workflow_call:
    inputs:
      php:
        description: PHP versions to test, in JSON format.
        default: '["8.1","8.2","8.3","8.4","8.5"]'
        required: false
        type: string
      codecov-php:
        description: PHP version to upload coverage to Codecov.
        default: 8.5
        required: false
        type: string
    secrets:
      CODECOV_TOKEN:
        description: Codecov upload token
        required: false

permissions:
  contents: read

jobs:
  tests:
    name: PHP ${{ matrix.php }} ${{ matrix.os }}

    env:
      extensions: pdo_sqlite

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov

      - name: Install Composer dependencies + required yiisoft/db-sqlite
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db-sqlite' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db-sqlite

      - name: Install yiisoft/db package.
        if: ${{ (github.event.pull_request.base.repo.name || github.event.repository.name) != 'db' }}
        uses: yiisoft/actions/install-packages/install-package@master
        with:
          package: db

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Sqlite --coverage-clover=coverage.xml --colors=always --display-warnings --display-deprecations

      - name: Upload coverage to Codecov.
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.php == inputs.codecov-php }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
