name: psalm

on:
  workflow_call:
    inputs:
      required-packages:
        description: List of required packages to install, in JSON format. For example '["db", "db-sqlite"]'.
        default: ''
        required: false
        type: string
      psalm-config:
        description: Psalm configuration file.
        default: psalm.xml
        required: false
        type: string
      os:
        description: Operating systems to test, in JSON format.
        default: '["ubuntu-latest"]'
        required: false
        type: string
      php:
        description: PHP versions to test, in JSON format.
        default: '["8.1","8.2","8.3","8.4"]'
        required: false
        type: string
      extensions:
        description: List of extensions to PHP.
        default:
        required: false
        type: string

permissions:
  contents: read

jobs:
  psalm:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout.
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          extensions: ${{ inputs.extensions }}
          tools: cs2pr

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - if: ${{ inputs.required-packages != '' }}
        name: Install required packages.
        uses: yiisoft/actions/install-packages@master
        with:
          packages: ${{ inputs.required-packages }}

      - name: Static analysis.
        run: vendor/bin/psalm --config="$INPUTS_PSALM_CONFIG" --shepherd --stats --output-format=github --php-version="$MATRIX_PHP"
        env:
          INPUTS_PSALM_CONFIG: ${{ inputs.psalm-config }}
          MATRIX_PHP: ${{ matrix.php }}
