name: rector

on:
  workflow_call:
    inputs:
      composer-command:
        description: Composer command to run
        default: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        required: false
        type: string
      required-packages:
        description: List of required packages to install, for example '["db", "db-sqlite"]'
        default: ''
        required: false
        type: string
      download-config:
        description: Download Rector configuration file
        default: false
        required: false
        type: boolean
      os:
        description: OS to test, separated by comma
        default: '["ubuntu-latest"]'
        required: false
        type: string
      php:
        description: PHP versions to test, separated by comma
        default: '["8.5"]'
        required: false
        type: string
      extensions:
        description: List of extensions to PHP
        required: false
        type: string
      repository:
        type: string
        required: false
    secrets:
      token:
        description: GitHub classic token with repo and workflow scopes
        required: false

jobs:
  rector:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          token: ${{ secrets.token || github.token }}
          ref: ${{ github.head_ref }}
          repository: ${{ inputs.repository }}
          persist-credentials: false

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@b604ade2a87db23f8871b7182e69ec5e75effb45
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ inputs.extensions }}
          coverage: none

      - name: Determine composer cache directory on Linux
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Cache dependencies installed with composer
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-

      - name: Install dependencies with composer
        run: $INPUTS_COMPOSER_COMMAND
        env:
          INPUTS_COMPOSER_COMMAND: ${{ inputs.composer-command }}

      - if: ${{ inputs.required-packages != '' }}
        name: Install required packages.
        uses: yiisoft/actions/install-packages@master
        with:
          packages: ${{ inputs.required-packages }}

      - name: Download rector config
        if: ${{ inputs.download-config == true}}
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/yiisoft/actions/main/config/rector.php -O rector.php

      - run: vendor/bin/rector process --ansi --output-format=github

      - name: Configure Git credentials
        env:
          GH_TOKEN: ${{ secrets.token || github.token }}
        run: git config --global credential.helper '!f() { echo username=x-access-token; echo password=$GH_TOKEN; }; f'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          commit_message: "Apply Rector changes (CI)"
          file_pattern: '*.php'
          disable_globbing: true
