name: GitHub Actions Security Analysis with zizmor 🌈

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  zizmor:
    name: Run zizmor 🌈
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create zizmor configuration
        run: |
          cat > .zizmor-shared.yml <<'YAML'
          rules:
            unpinned-uses:
              config:
                policies:
                  "yiisoft/*": any
          YAML

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: false
          annotations: true
          config: .zizmor-shared.yml
          persona: 'pedantic'
